name: CI # Define the name of the workflow

on: # Specify events that trigger the workflow
  push: # Trigger on pushes to the main branch
    branches:
  pull_request: # Trigger on pull requests targeting the main branch
    branches:
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  test: # Define the test job
    runs-on: ubuntu-latest # Use the latest Ubuntu runner environment

    steps:
      - name: Checkout repository # Step to fetch the repository code
        uses: actions/checkout@v4

      - name: Set up Node.js # Install the desired Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify Node.js version 20.x

      - name: Cache node modules # Cache dependencies to speed up builds
        uses: actions/cache@v3
        with:
          path: node_modules # Directory to cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: | # Fallback keys if exact match isn't found
            ${{ runner.os }}-node-

      - name: Run tests # Install dependencies and execute tests
        run: |
          npm install  # Install necessary packages
          npm test -- --verbose  # Run tests with detailed logs
